# Exercice 1

- Créer **deux scalaires** qui ont respectivement pour valeur 5 et 6, et additionnez-les

In [2]:
import numpy as np
scalaire1 = np.array(5)
scalaire2 = np.array(6)
sum = scalaire1 + scalaire2

- Afficher **le résultat** dans une fonction **print()** 

In [3]:
print(sum)

11


# Exercice 2

- Créer **trois vecteurs** qui ont pour valeur [1,2,3],[3,2,1] et [0,1,-1], et additionnez-les

In [4]:
vecteur1 = np.array([1,2,3])
vecteur2 = np.array([3,2,1])
vecteur3 = np.array([0,-1,1])
sum = vecteur1 + vecteur2 + vecteur3 

- Afficher **le résultat** dans une fonction **print()** 

In [5]:
print(sum)

[4 3 5]


- Afficher en-dessous **la dimension** de ce vecteur

In [6]:
print(sum.shape)

(3,)


# Exercice 3

- Créer **un scalaire** de valeur 0

In [7]:
scalaireNull = np.array(0)

- Créer **un vecteur** qui a pour valeur : [125, 2185, 321, 665, 17, -8] 

In [8]:
vector = np.array([125,2185,321,665,17,-8])

**Multipliez le scalaire et le vecteur** (pour cela utilisez l'opérateur *)

In [9]:
result = scalaireNull*vector

- Afficher **le résultat** dans une fonction **print()** 

In [10]:
print(result)

[0 0 0 0 0 0]


- **Que constatez-vous ?**

On constate que la multiplication d'un vecteur par un scalaire dans NumPy nous donne comme résultat un vecteur dont chaque élément de position **i** est produite par la multplication de scalaire par l'élément de la position **i** de vecteur

# Exercice 4

- Créer **un matrice de dimension 2x3** (peu importe les valeurs de ses éléments)

In [11]:
matrice = np.array([[4,0,1],[0,-2,9]])

- Vérifier que vous avez bien réussi à créer cette matrice en utilisant l'attribut **shape**

In [12]:
print(matrice.shape)

(2, 3)


# Exercice 5

- Créer **deux matrices** de **dimension 4x2**

In [14]:
matrice_1 = np.array([[1,0],[2,2],[4,-2],[8,1]])
matrice_2 = np.array([[1,4],[-2,2],[4,4],[-5,9]])

- Faites **une somme** de ces deux matrices

In [15]:
sum_matrice1_matrice2 = matrice_1 + matrice_2
print(sum_matrice1_matrice2)

[[ 2  4]
 [ 0  4]
 [ 8  2]
 [ 3 10]]
