**Ne pas oublier d'exécuter l'import de Numpy au début de votre notebook!**

In [1]:
import numpy as np

## Exercice 1

Récupérer l'élément à **la troisième ligne** et à **la cinquième colonne** de la matrice ci-dessous.

Récupérer **le dernier élément** de **la dernière ligne**

Récupérer **l'avant-dernier élément des lignes** et **le 6ème élément des colonnes**.

In [6]:
matrice_exercice_1 = np.array([[1,2,3,4,5,6,7,8,9,10],
                               [11,12,13,14,15,16,17,18,19,20],
                               [21,22,23,24,25,26,27,28,29,30],
                               [31,32,33,34,35,36,37,38,39,40],
                               [41,42,43,44,45,46,47,48,49,50]])

# Réponses :

print(matrice_exercice_1[2,4])
print(matrice_exercice_1[-1,-1])
print(matrice_exercice_1[-2,5])

25
50
36


## Exercice 2

- Faire un **slicing** en récupérant tous les éléments de **la 3ème à l'avant-dernière ligne exclus**.

- Faire un **slicing** en récupérant l'élément à **la 5ème colonne** de **la 5ème ligne** à **la 6ème ligne inclus**.

- Faire un slicing de la deuxième ligne à la quatrième ligne, de la troisième colonne à la huitième colonne.

- Faire un slicing : récupérer la ligne 3 de la 3ème à la 7ème colonne inclus

In [12]:
matrice_exercice_2 = np.array([[1,2,3,4,5,6,7,8,9,10],
                               [11,12,13,14,15,16,17,18,19,20],
                               [21,22,23,24,25,26,27,28,29,30],
                               [31,32,33,34,35,36,37,38,39,40],
                               [41,42,43,44,45,46,47,48,49,50],
                               [51,52,53,54,55,56,57,58,59,60],
                               [61,62,63,64,65,66,67,68,69,70],
                               [71,72,73,74,75,76,77,78,79,80]])

# Réponses :

print(matrice_exercice_2[-4])
print()
print(matrice_exercice_2[4,4])
print()
print(matrice_exercice_2[1:4,2:9])
print()
print(matrice_exercice_2[2,2:8])

[41 42 43 44 45 46 47 48 49 50]

45

[[13 14 15 16 17 18 19]
 [23 24 25 26 27 28 29]
 [33 34 35 36 37 38 39]]

[23 24 25 26 27 28]


## Exercice 3

- Récupérer tous les éléments aux indices pairs des lignes et des colonnes

- Récupérer tous les éléments avec un pas de 5.

- Faire un slicing de la 1ère à la 5ème ligne inclus et de la 6ème colonne à la dernière inclus. Récupérer les lignes avec un pas de 2 et les colonnes avec un pas de 1

In [16]:
matrice_exercice_3 = np.array([[1,2,3,4,5,6,7,8,9,10],
                               [11,12,13,14,15,16,17,18,19,20],
                               [21,22,23,24,25,26,27,28,29,30],
                               [31,32,33,34,35,36,37,38,39,40],
                               [41,42,43,44,45,46,47,48,49,50],
                               [51,52,53,54,55,56,57,58,59,60],
                               [61,62,63,64,65,66,67,68,69,70],
                               [71,72,73,74,75,76,77,78,79,80],
                               [81,82,83,84,85,86,87,88,89,90],
                               [91,92,93,94,95,96,97,98,99,100]])

#Réponses : 

print(matrice_exercice_3[0::2,0::2])
print()
print(matrice_exercice_3[0::5,0::5])
print()
print(matrice_exercice_3[0:6:2,5:10])

[[ 1  3  5  7  9]
 [21 23 25 27 29]
 [41 43 45 47 49]
 [61 63 65 67 69]
 [81 83 85 87 89]]

[[ 1  6]
 [51 56]]

[[ 6  7  8  9 10]
 [26 27 28 29 30]
 [46 47 48 49 50]]


## Exercice 4

- Assigner la valeur 5 à l'indice 3 du vecteur suivant.

- Assigner la valeur 9 au dernier indice du vecteur suivant

In [18]:
vecteur_exercice_4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

#Réponses : 

vecteur_exercice_4[3] = 5
vecteur_exercice_4[-1] = 9
print(vecteur_exercice_4)

[ 1  2  3  5  5  6  7  8  9 10 11 12  9]


## Exercice 5

- Assigner la valeur 1 à toute la première ligne

- Assigner à la dernière colonne des valeurs croissantes en commençant par la valeur 1.

- Assigner la valeur 5 aux éléments à la dernière ligne et aux colonnes allant de l'indice 1 à l'indice 3 inclus.

In [25]:
matrice_exercice_5 = np.array([[0,0,0,0,0], [2,2,2,2,-2], [3,3,3,3,-3], [4,4,4,4,-4], [5, 6, 6, 6, -5]])

# Réponses : 

matrice_exercice_5[0] = 1
matrice_exercice_5[:,-1] = [1,2,3,4,5]
matrice_exercice_5[-1,1:4] = 5
print(matrice_exercice_5)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
