**Importer Numpy**

In [1]:
import numpy as np

## Sorting

In [3]:
arr = np.array([5,4,0,2,3,1])

print(np.sort(arr))

[0 1 2 3 4 5]


In [4]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtring

<font color="brown">Getting some elements out of an existing array and creating a new array out of them is called filtering. In NumPy, you filter an array using a boolean index list</font>

In [5]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [6]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.
We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to

In [7]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


# Random Numbers in NumPy


**Import Random module**

In [9]:
from numpy import random

In [12]:
x = random.randint(100)
print(x)

44


In [16]:
x = random.rand()
print(x)

0.09074749779896074


In [18]:
x = random.randint(1000, size=(5))
print(x)

[  3 419 576 117 121]


In [19]:
x=random.randint(100, size=(5,3))

print(x)

[[87 30 24]
 [24 74 98]
 [79 35  3]
 [64 57 77]
 [42 13 71]]


In [21]:
x=random.rand(5,3)

print(x)

[[0.83817707 0.83884548 0.71873716]
 [0.96211692 0.26112893 0.83200826]
 [0.56700163 0.45736794 0.63322558]
 [0.06325593 0.84268196 0.96739471]
 [0.19946396 0.19622994 0.51216532]]


In [27]:
x = random.choice([3, 5, 7, 9])
# x = random.choice([3, 5, 7, 9],size=5) return a list of size 5
print(x)

9


# Random Data Distribution


**We can generate random numbers based on defined probabilities using the choice() method of the random module.**
**The choice() method allows us to specify the probability for each value.**

In [45]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)
sum = 0
for i in x:
    if i == 7:
        sum += 1
print(sum)

[7 7 7 5 7 3 3 3 7 5 7 7 7 3 7 7 7 7 7 7 7 7 7 7 7 3 5 7 5 7 7 5 5 7 7 7 7
 7 7 5 5 7 7 7 7 7 5 5 7 7 5 7 5 7 5 7 7 7 7 5 3 5 3 7 7 5 5 7 3 7 7 7 5 5
 5 7 5 7 5 7 7 3 7 3 7 7 7 7 5 7 7 7 7 7 7 5 3 5 7 5]
63
