# <center>**IV. Slicing conditionnel et squeeze**</center>

**Importer Numpy**

In [2]:
import numpy as np

### <center>**IV.1. Slicing conditionnel**</center>

### <center>**ndarray des booléens**</center>

**matrice 4x4**

In [3]:
matrice_a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
matrice_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**On veut connaître les éléments de la matrice qui sont supérieurs à 6**

In [4]:
matrice_b = (matrice_a>6)
print(matrice_b)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


**On veut connaître les éléments de la matrice qui sont paires**

In [5]:
matrice_a%2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

**Des conditions peuvent être établies entre un vecteur et une matrice** si ces deux ndarray respectent les règles du broadcasting que nous avons vues à l'épisode précédent.

In [6]:
vecteur_b = np.array([9,7,3,8])
vecteur_b 

array([9, 7, 3, 8])

**Condition : les valeurs des éléments de la matrice qui sont supérieures ou égales aux valeurs des éléments du vecteur.**

In [7]:
(matrice_a >= vecteur_b).all()

np.False_