**Importer Numpy**

In [1]:
import numpy as np

# <center>**I. Indexing et Slicing**</center>

### **<center>I.1 Les index</center>**

**Instancions un ndarray de dimension 2**

In [2]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**Récupérer le premier élément de la matrice**

In [3]:
matrice[0]

array([0, 1, 2, 3])

**Type de matrice[0]**

In [4]:
type(matrice[0])

numpy.ndarray

**Obtenir le premier élément de la première ligne de la matrice**

In [5]:
matrice[0, 0]

np.int64(0)

**Obtenir le troisième élément de la deuxième ligne de la matrice définis ci-dessous**

In [6]:
matrice[1,2]

np.int64(6)

### **<center>I.2 Les index négatifs</center>**

**Créons un vecteur composé de 10 éléments**

In [7]:
vecteur = np.array([1,2,3,4,5,6,7,8,9,10])
vecteur

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Récupérer le dérnier élément du vecteur**

In [8]:
vecteur[-1]

np.int64(10)

**Récupérer le quatrième élément en partant de la fin du vecteur**

In [9]:
vecteur[-4]

np.int64(7)

**Cela marche aussi avec les matrices**

In [10]:
matrice = np.array([[1,2],[3,4],[5,6]])
matrice[-1,-1]

np.int64(6)

### **<center>I.3 Slicing</center>**

**Instancions une matrice sur laquelle nous allons étudier le Slicing**

In [11]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**Récupérer les colonnes 2 et 3 de toutes les lignes**

In [12]:
matrice[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**Récupérer les 3 dernières colonnes des 3 dèrnieres lignes**

In [13]:
matrice[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

**Slicing sur un vecteur**

In [14]:
vecteur = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print(vecteur)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


**Récupérer les 4 dernièrs éléments du vecteur**

In [15]:
vecteur[-4:]
# vecteur[10:]

array([11, 12, 13, 14])

### **<center>Le pas</center>**

**Instancions un autre vecteur**

In [16]:
vecteur = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
vecteur[::2]

array([ 1,  3,  5,  7,  9, 11, 13])

**Récupérer tous les éléments aux indices paires**

In [17]:
vecteur[0:14:2]

array([ 1,  3,  5,  7,  9, 11, 13])

**Récupérer tous les éléments aux indices impaires**

In [18]:
vecteur[1:14:2]

array([ 2,  4,  6,  8, 10, 12, 14])

**Récupérer un élément sur trois**

In [19]:
vecteur[::3]

array([ 1,  4,  7, 10, 13])

### **<center>I.4 Assigner des valeurs</center>**

**Changer un seul élément dans un vecteur**

In [20]:
vecteur = np.array([1,2,3])
print(vecteur)
vecteur[-1] = 10
print(vecteur)

[1 2 3]
[ 1  2 10]


**Changer toutes les valeurs d'un vecteur une par une**

In [21]:
vecteur = np.array([1,2,3,4,5])
print(vecteur)

for i in range(vecteur.shape[0]):
    vecteur[i] = vecteur[i] * 5

print(vecteur)

[1 2 3 4 5]
[ 5 10 15 20 25]


**Changer un seul élément dans une matrice**

In [22]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(matrice)
print()

matrice[-2,-3] = 100
print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[  0   1   2   3]
 [  4   5   6   7]
 [  8 100  10  11]
 [ 12  13  14  15]]


**Changer toutes les valeurs d'une matrice 2x2**

In [23]:
matrice = np.array([[1,2],[3,4]])
print(matrice)
print()

for i in range(matrice.shape[0]):
    for j in range(matrice.shape[1]):
        matrice[i,j] = matrice[i,j] + 5

print(matrice)

[[1 2]
 [3 4]]

[[6 7]
 [8 9]]


**Affecter une même valeur à toute une ligne d'une matrice**

In [24]:
matrice = np.array([[1,2,14],[3,4,1],[5,7,9]])
print(matrice)
print()

matrice[0] = 0
print(matrice)

[[ 1  2 14]
 [ 3  4  1]
 [ 5  7  9]]

[[0 0 0]
 [3 4 1]
 [5 7 9]]


**Affecter un vecteur à la ligne d'une matrice**

In [25]:
matrice = np.array([[11,22,14],[30,14,12],[52,17,29],[52,17,92]])
print(matrice)
print()

matrice[2] = np.array([666,666,666])
print(matrice)
print()

vecteur = np.array([100,1000,10000])
matrice[-1] = vecteur
print(matrice)

[[11 22 14]
 [30 14 12]
 [52 17 29]
 [52 17 92]]

[[ 11  22  14]
 [ 30  14  12]
 [666 666 666]
 [ 52  17  92]]

[[   11    22    14]
 [   30    14    12]
 [  666   666   666]
 [  100  1000 10000]]


**Affecter les valeurs d'une liste à la ligne d'une matrice**

In [26]:
matrice = np.array([[11,22,14],[30,14,12],[52,17,29],[52,17,92]])
print(matrice)
print()

liste = [1,1,1]
matrice[2] = liste
print(matrice)

[[11 22 14]
 [30 14 12]
 [52 17 29]
 [52 17 92]]

[[11 22 14]
 [30 14 12]
 [ 1  1  1]
 [52 17 92]]


**Affecter une même valeur à toute une colonne d'une matrice**

In [27]:
matrice = np.array([[11,22,14],[30,14,12],[52,17,29],[52,17,92]])
print(matrice)
print()

matrice[:,-1] = -1
print(matrice)

[[11 22 14]
 [30 14 12]
 [52 17 29]
 [52 17 92]]

[[11 22 -1]
 [30 14 -1]
 [52 17 -1]
 [52 17 -1]]


**Affecter un vecteur à la colonne d'une matrice**

In [28]:
matrice = np.array([[11,22,14],[30,14,12],[52,17,29],[52,17,92]])
print(matrice)
print()

vecteur = np.array([1,2,3,4])
matrice[:,-1] = vecteur
print(matrice)

[[11 22 14]
 [30 14 12]
 [52 17 29]
 [52 17 92]]

[[11 22  1]
 [30 14  2]
 [52 17  3]
 [52 17  4]]


**Affecter les valeurs d'une liste à la colonne d'une matrice**

In [29]:
matrice = np.array([[11,22,14],[30,14,12],[52,17,29],[52,17,92]])
print(matrice)
print()

matrice[:,0] = [100,100,100,100]
print(matrice)

[[11 22 14]
 [30 14 12]
 [52 17 29]
 [52 17 92]]

[[100  22  14]
 [100  14  12]
 [100  17  29]
 [100  17  92]]


**Changer toutes les valeurs d'une matrice**

In [30]:
matrice[:,:] = 0
print(matrice)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


**ATTENTION : les crochets avec les double-points [:] sont indispensable pour assigner toutes les valeurs à votre ndarray !** si vous essayez d'affecter une valeur à votre ndarray sans ceux-ci, alors votre variable va devenir un int (nombre entier) 

In [31]:
matrice = 0
type(matrice)

int

### **<center>Affecter des valeurs avec le Slicing</center>**

**Affecter une valeur au croisement des lignes 2 et 3 et des colonnes 2 et 3 d'une matrice 5x5** 

In [32]:
matrice = np.array([[11,22,14,14,28],[30,14,12,14,8],[52,17,29,1,0],[52,17,92,1,12],[0,5,9,100,-9]])
print(matrice)
print()

matrice[2:4,2:4] = 666
print(matrice)

[[ 11  22  14  14  28]
 [ 30  14  12  14   8]
 [ 52  17  29   1   0]
 [ 52  17  92   1  12]
 [  0   5   9 100  -9]]

[[ 11  22  14  14  28]
 [ 30  14  12  14   8]
 [ 52  17 666 666   0]
 [ 52  17 666 666  12]
 [  0   5   9 100  -9]]


**Affecter la valeur 0 aux deux dernières colonnes, première ligne exclue**

In [33]:
matrice = np.array([[11,22,14,14,28],[30,14,12,14,8],[52,17,29,1,0],[52,17,92,1,12],[0,5,9,100,-9]])
print(matrice)
print()

matrice[1:,-2:] = 0
print(matrice)


[[ 11  22  14  14  28]
 [ 30  14  12  14   8]
 [ 52  17  29   1   0]
 [ 52  17  92   1  12]
 [  0   5   9 100  -9]]

[[11 22 14 14 28]
 [30 14 12  0  0]
 [52 17 29  0  0]
 [52 17 92  0  0]
 [ 0  5  9  0  0]]


### **<center>I.5 Elementwise properties (propriétés élément par élément)</center>**

**Ajouter 1 aux valeurs d'un vecteur**

In [34]:
vecteur = np.array([1,5,9])
vecteur+1

array([ 2,  6, 10])

**Ajouter 1 aux valeurs d'une matrice**

In [35]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
matrice+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**Rappel sur les listes et l'opérateur +**

In [36]:
List = [-1,-1,-1]
List+1

TypeError: can only concatenate list (not "int") to list

**Additionner la ligne d'une matrice a un vecteur**

In [117]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(matrice)
print()

vecteur = np.array([-1,-1,-1,-1])
matrice[0] = matrice[0] + vecteur
print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[-1  0  1  2]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**Additionner un vecteur à toutes les lignes d'une matrice**

In [121]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
vecteur = np.array([-1,-1,-1,-1])
print(matrice)
print()


matrice = matrice + vecteur

print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


**Soustraire les valeurs de deux vecteurs**

In [126]:
vecteur1 = np.array([1,2,6])
vecteur2 = np.array([2,1,3])
print(vecteur1-vecteur2)

[ 2  2 18]


**Multiplier un vecteur par une valeur**

In [123]:
vecteur = np.array([2,1,3])
scalaire = 5
print(scalaire*vecteur)

[10  5 15]


**Multiplier une matrice par une valeur**

In [124]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(matrice)
print()

matrice = matrice*10
print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]


**Multiplier une ligne d'une matrice par une valeur**

In [125]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(matrice)
print()

matrice[-1] = matrice[-1]*1000
print(matrice)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[    0     1     2     3]
 [    4     5     6     7]
 [    8     9    10    11]
 [12000 13000 14000 15000]]


**Multiplier toutes les lignes d'une matrice par un vecteur**

In [129]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
vecteur = np.array([-1,-1,-1,-1])
print(matrice)
print()

matrice = matrice * vecteur
print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


**Diviser deux vecteurs entre eux**

In [133]:
vecteur1 = np.array([1,2,6])
vecteur2 = np.array([2,1,3])
print(vecteur1/vecteur2)
print()
print(vecteur2/vecteur1)


[0.5 2.  2. ]

[2.  0.5 0.5]
