In [11]:
import numpy as np

In [12]:
np.__version__

'2.1.1'

Les scalaires

In [13]:
scalaire = np.array(3.15)
print(scalaire)

3.15


In [14]:
scalaire

array(3.15)

In [15]:
type(scalaire)

numpy.ndarray

In [16]:
type(3.15)

float

Les vecteur et ils s'appel aussi les tableaux a un dimension

In [17]:
vecteur = np.array(['khalid','ayoub','anouar','makrame'])

In [18]:
vecteur

array(['khalid', 'ayoub', 'anouar', 'makrame'], dtype='<U7')

In [19]:
print(vecteur)

['khalid' 'ayoub' 'anouar' 'makrame']


In [20]:
type(vecteur)

numpy.ndarray

In [21]:
type(['1','2','3'])

list

Une matrice ou bien un tableau à deux dimensions

In [22]:
matrice = np.array([[1,0,0],[0,1,0],[0,0,1]])

In [24]:
matrice

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
print(matrice)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
type(matrice)

numpy.ndarray

Connaître les dimensions d'un ndarray


In [27]:
scalaire.shape

()

In [29]:
vecteur.shape

(4,)

In [30]:
matrice.shape

(3, 3)

In [34]:
matrice_2 = np.array([[1,4,0],[-1,0,2]])
matrice_2.shape

(2, 3)

In [36]:
matrice_2.shape[1]

3

In [37]:
matrice_2.shape[0]

2

In [38]:
scalaire_dimension_1 = np.array([1])
scalaire_dimension_1

array([1])

In [40]:
print(scalaire.shape)
print(scalaire_dimension_1.shape)

()
(1,)
