# <center>**III. Quelques fonctions de Numpy**</center>

**Importer Numpy**

In [4]:
import numpy as np

### <center>**III.1. Bases nécessaire à l'utilisation de fonctions universelles**</center>

Les fonctions universelles permettent de travailler sur des ndarray élément par élément (Elementwise functions).

Documentation Numpy sur les fonctions universelles (ufunc) : https://numpy.org/doc/stable/reference/ufuncs.html

Le premier type de fonction évoqué sur la documentation de Numpy sont celles de type "Broadcasting". Nous allons commencer par étudier celles-ci.

### <center>**Broadcasting**</center>

**Instancions un vecteur ligne, un vecteur colonne et une matrice**

In [5]:
vect_ligne = np.array([1,2,3])

In [6]:
vect_colonne = np.array([[1],[2],[3]])

In [7]:
matrice = np.array([[1,2,3],[4,5,6],[7,8,9]])

**Affichons les dimensions de nos ndarray**

In [8]:
print('Dimension de vecteur ligne',vect_ligne.shape)

Dimension de vecteur ligne (3,)


In [9]:
print('Dimension de vecteur colonne',vect_colonne.shape)

Dimension de vecteur colonne (3, 1)


In [10]:
print('Dimension de la matrice',matrice.shape)

Dimension de la matrice (3, 3)


**Additionner le vecteur ligne et la matrice**

In [11]:
matrice + vect_ligne

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

Le vecteur ligne vect_ligne est converti **(broadcast)** en une matrice de dimension **3x3** ressemblant à ceci *np.array([1,2,3],[1,2,3],[1,2,3]).*
Chaque ligne de la matrice est ensuite additionnée avec le vecteur ligne.
L'opérateur + est l'équivalent de la méthode **np.add()**, qui permet de faire **un broadcast** des ndarray de dimensions différentes.

In [12]:
np.add(matrice,vect_ligne)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

**Additionner le vecteur colonne et la matrice**

In [13]:
np.add(matrice,vect_colonne)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

1. Les ndarrays ont tous la même shape.

2. Les ndarrays ont tous le même nombre de dimension et la longueur de chaque dimension doit être soit similaire soit égale à 1.

3. Les ndarrays qui n'ont pas assez de dimension peuvent se voir ajouter une dimension de longueur 1 pour satisfaire la deuxième propriété.

### <center>**Type Casting**</center>

**Convention d'int en float**

In [14]:
vecteur = np.array([1,2,3,4])
matrice = np.array([[1,2,3,4], [5,6,7,8]])

print(vecteur.dtype)
print(matrice.dtype)

resultat = np.add(vecteur,matrice, dtype=np.float32)
print(resultat.dtype)
print(resultat)

int64
int64
float32
[[ 2.  4.  6.  8.]
 [ 6.  8. 10. 12.]]


**Convention d'int en string**

In [15]:
vecteur = np.array([1,2,3,4])
matrice = np.array([[1,2,3,4], [5,6,7,8]])

print(vecteur.dtype)
print(matrice.dtype)

resultat = np.add(vecteur,matrice, dtype=np.str_)
print(resultat.dtype)
print(resultat)

int64
int64
<U42
[['11' '22' '33' '44']
 ['15' '26' '37' '48']]


### <center>**Utliser une fonction sur un axe donné**</center>

**Matrice de dimension 2x5**

In [16]:
matrice = np.array([[1,2,3,4,5],[6,7,8,9,10]])

**Moyenne arithmétique des colonnes**

In [17]:
np.mean(matrice, axis=0)

array([3.5, 4.5, 5.5, 6.5, 7.5])

**Moyenne arithmétique des lignes**

In [18]:
np.mean(matrice, axis=1)

array([3., 8.])

### <center>**III.2. Quelques exemples de fonctionnement de fonctions universelles**</center>

### <center>**La fonction negative()**</center>

**Scalaire**

In [19]:
a1 = np.array(5)
s1 = np.negative(a1)
print(s1)

-5


**Vecteur**

In [20]:
vecteur = np.array([2,1,0,-1,-2])
print(np.negative(vecteur))

[-2 -1  0  1  2]


**Matrice**

In [21]:
matrice = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.negative(matrice))

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]]


### <center>**La fonction power()**</center>

**Scalaire et scalaire**

In [22]:
scalaire = np.array(3)
puissance = np.array(2)

np.power(scalaire,puissance)

np.int64(9)

**Vecteur et scalaire**

In [23]:
scalaire = np.array(3)
vecteur = np.array([1,2,3])
np.power(vecteur,scalaire)

array([ 1,  8, 27])

**Vecteur et vecteur**

In [24]:
vecteur1 = np.array([1,2,3])
vecteur2 = np.array([4,5,6])
np.power(vecteur2,vecteur1)

array([  4,  25, 216])

**Matrice et scalaire**

In [25]:
matrice = np.array([[1,2,3],[4,5,6],[7,8,9]])
scalaire = np.array(2)
np.power(matrice,scalaire)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

**Matrice et vecteur**

In [26]:
matrice = np.array([[1,2,3],[4,5,6],[7,8,9]])
vecteur = np.array([1,2,3])
np.power(matrice,vecteur)

array([[  1,   4,  27],
       [  4,  25, 216],
       [  7,  64, 729]])

**Matrice et matrice**

In [27]:
matrice_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrice_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.power(matrice_1,matrice_2)

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

### <center>**La fonction conjugate()**</center>

**Scalaire**

In [28]:
scalaire = np.array(1+2j)
np.conjugate(scalaire)

np.complex128(1-2j)

**Vecteur**

In [29]:
vecteur = np.array([1j,5-1j,5+2j,1])
print(np.conjugate(vecteur))

[0.-1.j 5.+1.j 5.-2.j 1.-0.j]


**Matrice**

In [30]:
matrice = np.array([[1-4j,2j],[3-1j,4+2j]])
np.conjugate(matrice)

array([[1.+4.j, 0.-2.j],
       [3.+1.j, 4.-2.j]])

### <center>**La fonction around()**</center>

**Scalaire**

In [31]:
scalaire = np.array(5.6765465,dtype=float)
np.around(scalaire,decimals=1)

np.float64(5.7)

**Vecteur**

In [32]:
vect_a = np.array([1.3245, 3.2168, 9.8541, 6.3210, 1.0234, 7.850])
np.around(vect_a,decimals=2)

array([1.32, 3.22, 9.85, 6.32, 1.02, 7.85])

**Matrice**

In [33]:
mat_a = np.array([[1.213, 3.654, 6.654, 9.201, 4.403], 
                  [5.021, 5.558, 6.321, 7.013, 8.631]])
np.around(mat_a,decimals=2)

array([[1.21, 3.65, 6.65, 9.2 , 4.4 ],
       [5.02, 5.56, 6.32, 7.01, 8.63]])

### <center>**La fonction arange()**</center>

In [39]:
vecteur_1 = np.arange(1,10)
print(vecteur_1)
print()

vecteur_2 = np.arange(0,101,10)
print(vecteur_2)

[1 2 3 4 5 6 7 8 9]

[  0  10  20  30  40  50  60  70  80  90 100]


### <center>**La fonction reshape()**</center>

In [43]:
matrice = np.arange(10000).reshape(100,100)
print(matrice)


[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


### <center>**Les fonctions géométriques**</center>

In [48]:
from numpy import pi
vecteur = np.array([0,pi/3,pi])
print(np.sin(vecteur))
print(np.cos(vecteur))
print(np.tan(vecteur))

[0.00000000e+00 8.66025404e-01 1.22464680e-16]
[ 1.   0.5 -1. ]
[ 0.00000000e+00  1.73205081e+00 -1.22464680e-16]


### <center>**III.3. Quelques opérations classiques**</center>

In [49]:
matrice_identite = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(matrice_identite==1)

[[ True False False]
 [False  True False]
 [False False  True]]


In [50]:
print(10*np.cos(matrice_identite))

[[ 5.40302306 10.         10.        ]
 [10.          5.40302306 10.        ]
 [10.         10.          5.40302306]]


**Le produit elementwise de deux matrices**

In [51]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print(A*B)

[[2 0]
 [0 4]]


**Le produit mathématique de deux matrices**

In [52]:
print(A@B)

[[5 4]
 [3 4]]


Autre méthode

In [53]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [74]:
matrix = np.arange(20).reshape(5,4)
print(matrix)
print()

print(matrix.cumsum(axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]
 [40 45 50 55]]
