**Importer Numpy**

In [1]:
import numpy as np

# <center>**I. Indexing et Slicing**</center>

### **<center>I.1 Les index</center>**

**Instancions un ndarray de dimension 2**

In [3]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**Récupérer le premier élément de la matrice**

In [8]:
matrice[0]

array([0, 1, 2, 3])

**Type de matrice[0]**

In [9]:
type(matrice[0])

numpy.ndarray

**Obtenir le premier élément de la première ligne de la matrice**

In [11]:
matrice[0, 0]

np.int64(0)

**Obtenir le troisième élément de la deuxième ligne de la matrice définis ci-dessous**

In [18]:
matrice[1,2]

np.int64(6)

### **<center>I.2 Les index négatifs</center>**

**Créons un vecteur composé de 10 éléments**

In [20]:
vecteur = np.array([1,2,3,4,5,6,7,8,9,10])
vecteur

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Récupérer le dérnier élément du vecteur**

In [24]:
vecteur[-1]

np.int64(10)

**Récupérer le quatrième élément en partant de la fin du vecteur**

In [27]:
vecteur[-4]

np.int64(7)

**Cela marche aussi avec les matrices**

In [32]:
matrice = np.array([[1,2],[3,4],[5,6]])
matrice[-1,-1]

np.int64(6)

### **<center>I.3 Slicing</center>**

**Instancions une matrice sur laquelle nous allons étudier le Slicing**

In [33]:
matrice = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(matrice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**Récupérer les colonnes 2 et 3 de toutes les lignes**

In [42]:
matrice[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**Récupérer les 3 dernières colonnes des 3 dèrnieres lignes**

In [44]:
matrice[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

**Slicing sur un vecteur**

In [47]:
vecteur = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print(vecteur)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


**Récupérer les 4 dernièrs éléments du vecteur**

In [48]:
vecteur[-4:]
# vecteur[10:]

array([11, 12, 13, 14])