In [11]:
import numpy as np

In [12]:
np.__version__

'2.1.1'

Les scalaires

In [13]:
scalaire = np.array(3.15)
print(scalaire)

3.15


In [14]:
scalaire

array(3.15)

In [15]:
type(scalaire)

numpy.ndarray

In [16]:
type(3.15)

float

Les vecteur et ils s'appel aussi les tableaux a un dimension

In [17]:
vecteur = np.array(['khalid','ayoub','anouar','makrame'])

In [18]:
vecteur

array(['khalid', 'ayoub', 'anouar', 'makrame'], dtype='<U7')

In [19]:
print(vecteur)

['khalid' 'ayoub' 'anouar' 'makrame']


In [20]:
type(vecteur)

numpy.ndarray

In [21]:
type(['1','2','3'])

list

Une matrice ou bien un tableau à deux dimensions

In [22]:
matrice = np.array([[1,0,0],[0,1,0],[0,0,1]])

In [24]:
matrice

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
print(matrice)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
type(matrice)

numpy.ndarray

Connaître les dimensions d'un ndarray


In [27]:
scalaire.shape

()

In [29]:
vecteur.shape

(4,)

In [30]:
matrice.shape

(3, 3)

In [34]:
matrice_2 = np.array([[1,4,0],[-1,0,2]])
matrice_2.shape

(2, 3)

In [41]:
print(matrice_2[1][2])

2


In [42]:
matrice_2.shape[1]

3

In [43]:
matrice_2.shape[0]

2

In [44]:
scalaire_dimension_1 = np.array([1])
scalaire_dimension_1

array([1])

In [45]:
print(scalaire.shape)
print(scalaire_dimension_1.shape)

()
(1,)


In [46]:
tableau1 = [1,2,45,6]
len(tableau1)

4

In [47]:
tableau2 = [[1,4,8],[0,0,7]]
len(tableau2)

2

L'opérateur somme "+"

In [48]:
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [50]:
scalaire_1 = np.array(2)
scalaire_2 = np.array(3)
print(scalaire_1 + scalaire_2)

5


In [53]:
vecteur_1 = np.array([1,2,3])
vecteur_2 = np.array([-1,-2,-3])
somme_vecteurs = vecteur_1 + vecteur_2
print(vecteur_1, "+", vecteur_2, "=", somme_vecteurs)

[1 2 3] + [-1 -2 -3] = [0 0 0]


In [54]:
matrice_1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
matrice_2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
somme_matrices = matrice_1 + matrice_2
print(matrice_1)
print("+")
print(matrice_2)
print("=")
print(somme_matrices)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
+
[[1 0 0]
 [0 1 0]
 [0 0 1]]
=
[[2 0 0]
 [0 2 0]
 [0 0 2]]


Les fonctions mathématiques

In [55]:
from math import log

In [56]:
log(15)

2.70805020110221

In [57]:
liste = [1,2,3,4]
log(list)

TypeError: must be real number, not type

In [58]:
liste = np.array([1,2,3,4])
np.log(liste)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [59]:
matrice = np.array([[1,4,16],[9,25,4]])
np.sqrt(matrice)

array([[1., 2., 4.],
       [3., 5., 2.]])

La longueur

In [60]:
liste_de_listes = [[1,2],[0,5,7],[4,8,9,3],[1,7,14,9,6]]
liste_de_listes

[[1, 2], [0, 5, 7], [4, 8, 9, 3], [1, 7, 14, 9, 6]]

In [64]:
matrice_erreur = np.array(liste_de_listes)
matrice_erreur

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.