# <center>**III. Quelques fonctions de Numpy**</center>

**Importer Numpy**

In [88]:
import numpy as np

### <center>**III.1. Bases nécessaire à l'utilisation de fonctions universelles**</center>

Les fonctions universelles permettent de travailler sur des ndarray élément par élément (Elementwise functions).

Documentation Numpy sur les fonctions universelles (ufunc) : https://numpy.org/doc/stable/reference/ufuncs.html

Le premier type de fonction évoqué sur la documentation de Numpy sont celles de type "Broadcasting". Nous allons commencer par étudier celles-ci.

### <center>**Broadcasting**</center>

**Instancions un vecteur ligne, un vecteur colonne et une matrice**

In [89]:
vect_ligne = np.array([1,2,3])

In [90]:
vect_colonne = np.array([[1],[2],[3]])

In [91]:
matrice = np.array([[1,2,3],[4,5,6],[7,8,9]])

**Affichons les dimensions de nos ndarray**

In [92]:
print('Dimension de vecteur ligne',vect_ligne.shape)

Dimension de vecteur ligne (3,)


In [93]:
print('Dimension de vecteur colonne',vect_colonne.shape)

Dimension de vecteur colonne (3, 1)


In [94]:
print('Dimension de la matrice',matrice.shape)

Dimension de la matrice (3, 3)


**Additionner le vecteur ligne et la matrice**

In [95]:
matrice + vect_ligne

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

Le vecteur ligne vect_ligne est converti **(broadcast)** en une matrice de dimension **3x3** ressemblant à ceci *np.array([1,2,3],[1,2,3],[1,2,3]).*
Chaque ligne de la matrice est ensuite additionnée avec le vecteur ligne.
L'opérateur + est l'équivalent de la méthode **np.add()**, qui permet de faire **un broadcast** des ndarray de dimensions différentes.

In [96]:
np.add(matrice,vect_ligne)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

**Additionner le vecteur colonne et la matrice**

In [97]:
np.add(matrice,vect_colonne)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

1. Les ndarrays ont tous la même shape.

2. Les ndarrays ont tous le même nombre de dimension et la longueur de chaque dimension doit être soit similaire soit égale à 1.

3. Les ndarrays qui n'ont pas assez de dimension peuvent se voir ajouter une dimension de longueur 1 pour satisfaire la deuxième propriété.

### <center>**Type Casting**</center>

**Convention d'int en float**

In [98]:
vecteur = np.array([1,2,3,4])
matrice = np.array([[1,2,3,4], [5,6,7,8]])

print(vecteur.dtype)
print(matrice.dtype)

resultat = np.add(vecteur,matrice, dtype=np.float32)
print(resultat.dtype)
print(resultat)

int64
int64
float32
[[ 2.  4.  6.  8.]
 [ 6.  8. 10. 12.]]


**Convention d'int en string**

In [99]:
vecteur = np.array([1,2,3,4])
matrice = np.array([[1,2,3,4], [5,6,7,8]])

print(vecteur.dtype)
print(matrice.dtype)

resultat = np.add(vecteur,matrice, dtype=np.str_)
print(resultat.dtype)
print(resultat)

int64
int64
<U42
[['11' '22' '33' '44']
 ['15' '26' '37' '48']]


### <center>**Utliser une fonction sur un axe donné**</center>

**Matrice de dimension 2x5**

In [100]:
matrice = np.array([[1,2,3,4,5],[6,7,8,9,10]])

**Moyenne arithmétique des colonnes**

In [101]:
np.mean(matrice, axis=0)

array([3.5, 4.5, 5.5, 6.5, 7.5])

**Moyenne arithmétique des lignes**

In [102]:
np.mean(matrice, axis=1)

array([3., 8.])

### <center>**III.2. Quelques exemples de fonctionnement de fonctions universelles**</center>

### <center>**La fonction negative()**</center>

**Scalaire**

In [103]:
a1 = np.array(5)
s1 = np.negative(a1)
print(s1)

-5


**Vecteur**

In [104]:
vecteur = np.array([2,1,0,-1,-2])
print(np.negative(vecteur))

[-2 -1  0  1  2]


**Matrice**

In [105]:
matrice = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.negative(matrice))

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]]


### <center>**La fonction power()**</center>

**Scalaire et scalaire**

In [106]:
scalaire = np.array(3)
puissance = np.array(2)

np.power(scalaire,puissance)

np.int64(9)

**Vecteur et scalaire**

In [107]:
scalaire = np.array(3)
vecteur = np.array([1,2,3])
np.power(vecteur,scalaire)

array([ 1,  8, 27])

**Vecteur et vecteur**

In [108]:
vecteur1 = np.array([1,2,3])
vecteur2 = np.array([4,5,6])
np.power(vecteur2,vecteur1)

array([  4,  25, 216])

**Matrice et scalaire**

In [109]:
matrice = np.array([[1,2,3],[4,5,6],[7,8,9]])
scalaire = np.array(2)
np.power(matrice,scalaire)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

**Matrice et vecteur**

In [110]:
matrice = np.array([[1,2,3],[4,5,6],[7,8,9]])
vecteur = np.array([1,2,3])
np.power(matrice,vecteur)

array([[  1,   4,  27],
       [  4,  25, 216],
       [  7,  64, 729]])

**Matrice et matrice**

In [111]:
matrice_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrice_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.power(matrice_1,matrice_2)

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

### <center>**La fonction conjugate()**</center>

**Scalaire**

In [112]:
scalaire = np.array(1+2j)
np.conjugate(scalaire)

np.complex128(1-2j)

**Vecteur**

In [113]:
vecteur = np.array([1j,5-1j,5+2j,1])
print(np.conjugate(vecteur))

[0.-1.j 5.+1.j 5.-2.j 1.-0.j]


**Matrice**

In [114]:
matrice = np.array([[1-4j,2j],[3-1j,4+2j]])
np.conjugate(matrice)

array([[1.+4.j, 0.-2.j],
       [3.+1.j, 4.-2.j]])

### <center>**La fonction around()**</center>

**Scalaire**

In [115]:
scalaire = np.array(5.6765465,dtype=float)
np.around(scalaire,decimals=1)

np.float64(5.7)

**Vecteur**

In [116]:
vect_a = np.array([1.3245, 3.2168, 9.8541, 6.3210, 1.0234, 7.850])
np.around(vect_a,decimals=2)

array([1.32, 3.22, 9.85, 6.32, 1.02, 7.85])

**Matrice**

In [118]:
mat_a = np.array([[1.213, 3.654, 6.654, 9.201, 4.403], 
                  [5.021, 5.558, 6.321, 7.013, 8.631]])
np.around(mat_a,decimals=2)

array([[1.21, 3.65, 6.65, 9.2 , 4.4 ],
       [5.02, 5.56, 6.32, 7.01, 8.63]])